### PR TITLE
Fix perform_later with multiple arguments

### PR DESCRIPTION
**Pull request by felipecsl**

### CODE REVIEW

**Comment by KensoDev** [comment]
Was this caused by the previous pull?

**Comment by felipecsl** [comment]
Yeah.. we had no tests for this scenario with multiple arguments.

**Comment by KensoDev** [comment]
First thing I thought about after accepting the pull was EXACTLY that.
Turns out, that I was correct.

Previous versions (before that pull) were working as expected with no issues.

Thanks for the contribution

**Comment by felipecsl** [comment]
:thumbsup:

**Pull request merged**
